name: Build and Deploy Documentation

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Convert Obsidian Vault to HTML
      run: |
        docker run --rm \
          -v "$(pwd)/hammy-docs:/root/vault" \
          -v "$(pwd)/hammy-docs-html:/root/vault_html" \
          adventum/obsidian-exporter

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./hammy-docs-html
        publish_branch: gh-pages  # The branch GitHub Pages uses